import { TabClass } from '../models';

export const tabData: TabClass[] = [
  {
    title: '推荐',
    name: 'recommend',
    icon: $r("app.media.ic_recommend")
  },
    {
    title: '发现',
    name: 'find',
    icon: $r("app.media.ic_find")
  },
    {
    title: 'music',
    name: 'home',
    icon: $r("app.media.ic_logo")
  },
    {
    title: '动态',
    name: 'moment',
    icon: $r("app.media.ic_moment")
  },
    {
    title: '我的',
    name: 'mine',
    icon: $r("app.media.ic_mine")
  }
];